name: Release
on:
  push:
    branches: [master]

jobs:
  release:
    name: Release Workflow
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Step 2: Set up Python environment
      - name: Setup Python Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install Python dependencies
      - name: Install Python Dev Dependencies
        run: pip install --upgrade pip && pip install -r server/requirements-dev.txt

      - name: Install Python Main Dependencies
        run: pip install -r requirements.txt

      # Step 4: Run Python linters and tests
      - name: Run Pre-Commit Hooks
        run: pre-commit run --all-files

      - name: Run Python Tests
        run: pytest server --verbose

      # Step 5: Set up Node.js environment
      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      # Step 6: Install and build Node.js dependencies
      - name: Install Node.js Dependencies
        run: npm ci && npm run compile

      - name: Build UI
        run: |
          cd ui
          npm ci
          npm run build

      # Step 7: Run Semantic Release
      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx semantic-release

      # Step 8: Optionally Publish to VS Code Marketplace
      # Uncomment the following step if VS Code Marketplace publishing is required
      # - name: Publish to VS Code Marketplace
      #   if: ${{ success() }}
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}
      #   run: npx vsce publish -p $VSCE_PAT
