name: Release
on:
  push:
    branches: [master]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci && npm run compile

      - name: Build UI
        run: cd ui && npm ci && npm run build

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: npx semantic-release

      # - name: Publish to VS Code Marketplace
      #   if: ${{ success() }}
      #   env:
      #     VSCE_PAT: ${{ secrets.VSCE_PAT }}
      #   run: npx vsce publish -p $VSCE_PAT
